--- a/decoupled/60/0.8_0.2/160/pydata_xarray/xarray/tests/test_dataset.py
+++ b/decoupled/60/0.8_0.2/160/pydata_xarray/xarray/tests/test_dataset.py
@@ -6557,6 +6557,8 @@
 @pytest.mark.filterwarnings("error")

 @pytest.mark.parametrize("ds", (2,), indirect=True)

 @pytest.mark.parametrize("name", ("mean", "max"))

+import xarray as xr

+

 def test_raise_no_warning_dask_rolling_assert_close(ds, name):

     """

     This is a puzzle â€” I can't easily find the source of the warning. It

@@ -6571,6 +6573,20 @@
     actual = getattr(rolling_obj, name)()

     expected = getattr(getattr(ds.rolling(time=4), name)().rolling(x=3), name)()

     assert_allclose(actual, expected)

+

+# Fix the trailing whitespace in the string representation of DatasetGroupBy

+xr.DatasetGroupBy.__repr__ = lambda self: self._repr()

+

+def _repr(self):

+    return (f"{self.__class__.__name__}, grouped over '{self._dim}'\n"

+            f"{self._groups_repr()}")

+

+# Example usage

+ds = xr.Dataset(

+    {"foo": (("x", "y"), np.random.rand(4, 3))},

+    coords={"x": [10, 20, 30, 40], "letters": ("x", list("abba"))},

+)

+print(str(ds.groupby("letters")))

 

 

 @pytest.mark.parametrize("dask", [True, False])
